### ISSUE TITLE
AVX2

### ISSUE THREAD

**Issue by Alex313031** [justclueless/chromium-win64#1]
I would recommend using the build.gn for linux/windows from my Thorium-AVX2 repository (it won't add any of the Thorium specific bits, it just contains Robs optimizations as well as some optimizations of my own and has mtune set to generic so that it doesn't optimize only for haswell.

https://github.com/Alex313031/Thorium-AVX2/tree/main/build/config

**Comment by justclueless** [comment]
@Alex313031 Thanks will take a look soon

**Comment by Lehner82** [comment]
Does the new release have these optimizations ?

**Comment by justclueless** [comment]
Yes they do, I just forgot to mention them in the release notes. 
They have been used since this repo started since most of them were provided by Rob back on woolyss (with the exception of polly). I don't plan to do polly because it takes too long.

**Comment by Alex313031** [comment]
@justclueless Same with polly. Can I have a copy of the main BUILD.gn as well as the win BUILD.gn that you are using? Perhaps you should upload them to a folder here like in my avx2 repo > https://github.com/Alex313031/Thorium-AVX2/

I want to compare our files to see the differences to see if theres something I can take from your file or something you can take from mine to make one/both of our releases better.

Thanks for continuing Robs work, because if people don't want thorium and want a performant chromium release for windows, you're all thats left.

**Comment by justclueless** [comment]
@Alex313031 I think I uploaded one a while back on woolyss when someone else asked. I'll try to remember to upload next time I build. 
But they should be the same as Rob's from way back when.

**Comment by justclueless** [comment]
@Alex313031 

build/config/compiler/build.gn
https://pastebin.com/bhwBFqEY

build/config/win/build.gn
https://pastebin.com/LVMxev94
