### ISSUE TITLE
Performance comparision

### ISSUE THREAD

**Issue by dabugen** [justclueless/chromium-win64#2]
I did a 30-minute benchmark (all 3 instances started in sync) with the app EA Studio that I am running 24/7 in Chromium and hence always test for the fastest builds. Interesting results can be seen in the screenshot. Just thought I´d share. Thanks for the good work and steady performance improvements!
![Untitled](https://user-images.githubusercontent.com/22604901/164535201-3b25aa24-d07d-4f9d-8832-bfe3df99b895.png)

**Comment by justclueless** [comment]
Thanks for the feedback. 
I'm not familiar with the computations being run in your scenarios, but my build seems to have the lowest number indicated by your red circle. Is lower better or higher number better? Also may I know if you're using an Intel or AMD cpu?

**Comment by dabugen** [comment]
Thanks for your reply. I am on a Ryzen 3950X. Higher is better, it´s the number of systems generated during that 30 minutes test run. I´ve had a discussion about these results with Alex, maybe you want to join? [](https://github.com/Alex313031/Thorium-AVX2/issues/11)

Thank you.

**Comment by justclueless** [comment]
@dabugen Yeah, I certainly don't do as many optimizations as Alex's builds. 
I think the community at Woolyss is already finding AVX2 builds to be too niche. I don't have the time to be building specific releases like Alex, so modest performance bumps are all I ask. 

There are times where I also do a specific build for myself, as a learning exercise, but yeah, not too comfortable releasing them in public.
