### ISSUE TITLE
i3

### ISSUE THREAD

**Issue by trimechee** [justclueless/chromium-win64#4]
Hello, thank you for the new version !  i see in the description" For Haswell CPUs and above", i have processor intel(R) Core(TM) i3-6006U CPU , is this compatible with this new version od Chromium-win64 please ?

**Comment by justclueless** [comment]
yes i think it should work

**Comment by justclueless** [comment]
1) quick google search says your CPU supports HEVC hardware decode, so it's probably going to be more efficient than software decode. Having said that, HEVC is way more complex than H264.

2) I'm on windows and HEVC works for me, so no, it's not a chromeOS thing. Youtube, dailymotion...etc will work regardless of HEVC support, I don't think they use it?

3) I think power consumption depends more on what you're doing. Example; if you're playing games then yes, fans will probably run louder. Checking your email, probably not?

**Comment by trimechee** [comment]
Very interesting ! Thank you very much for for your patience and kindness and important help and all your efforts to make this wonderful browser :)
